config/routes.rb
Rails.application.routes.draw do


#会員側のルーティング#

  scope module: :members do
    get '/' => 'home#top', as: 'top_path'
    get 'home/about' => 'home#about'
    get 'members/my_page' => 'members#show'
    get 'members/unsubscribe' => 'members#unsubscribe'
    patch 'members/withdraw' => 'members#withdraw'
    get 'members/edit_pass' => 'members#edit_pass'
    patch 'members/update_pass' => 'members#update_pass'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resource :members, only: [:edit, :update, :show]
    resources :carts, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    
    resources :items, only: [:index, :show] do
      resource :likes, only: [:create, :destroy]
    end
    
    resources :genres, only: [:show]
    resources :items, only: [:index, :show] do
      # collection do
      #   search 'search'
      # end
    end

    resources :genres, only: [:show]
    resources :orders, only: [:index, :new, :create, :show, :update]
    post 'order/confirm' => 'orders#confirm', as: 'order_confirm'
    get "order/thanks" => 'orders#thanks', as: 'order_thanks'

    devise_for :members

  end

  #管理者側のルーティング

  namespace :admins do
    get '' => 'tops#top'
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    resources :items, only: [:index, :show, :edit, :update, :create, :new]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :members, only: [:index, :show, :edit, :update] do
    get "orders/confirm"
    end
  end

  scope module: :admins do #URLがadmins_admins_sign_inのように冗長にならないようにscope muduleを使用
    devise_for :admins
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :member
	has_many :order_items
	has_many :items, through: :order_items

	enum payment_method: [:クレジットカード, :銀行振込 ]
	enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

end

app/controllers/admins/members_controller.rb
class Admins::MembersController < Admins::Base

  def index
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admins_member_path(@member), success: 'お客様情報が更新されました！'
    else
      flash[:danger] = 'お客様の情報を更新出来ませんでした。空欄の箇所はありませんか？'
      render :index
    end
  end


  private
  def member_params
    params.require(:member).permit(:is_deleted, :email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < Admins::Base
  before_action :set_order_item, only: [:update]

  def index
    @all_order = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_item = OrderItem.find(params[:id])
  end

  def confirm
    @member_order = Member.find(params[:member_id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(orders_params)
    #注文ステータスが入金確認なら下の事をする
    if @order.order_status == "入金確認"
    #製作ステータスを「製作待ちに」更新
      @order.order_items.update(making_status: 1)
    end
    redirect_to admins_order_path(@order)
  end

  private
  def orders_params
    params.require(:order).permit(:member_id, :payment_method, :order_status, :postal_code, :address, :name, :deliver_charge, :total_payment, order_items_attributes: [:order_id, :item_id, :amount, :past_price, :making_status])
  end

  def set_order_item
      @order_item = OrderItem.find(params[:id])
  end
end

app/controllers/members/addresses_controller.rb
class Members::AddressesController < Members::Base

  before_action :set_member

  def index
    @address = Address.new
    @addresses = @member.addresses
  end

  def create
    @address = Address.new(address_params)
    @address.member_id = current_member.id
    @address.save
    redirect_to addresses_path
  end

  def edit
    @address = Address.find(params[:id])

  end

  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to addresses_path
  end

  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to addresses_path

  end

  private

  def set_member
    @member = current_member
  end
  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end

end

app/controllers/members/application_controller copy.rb
class Members::ApplicationController < ActionController::Base
  layout 'members'
before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
      member_top_path
  end


  def after_sign_out_path_for(resource)
      new_member_session_path
  end


  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])# 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
      devise_parameter_sanitizer.permit(:sign_in, keys:[:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end
#オカタクメモ1：上記のcofigure(以下ストロングパラメーターが分かりやすいのでそう呼ぶ)以下の記載がないとunpermitted.parameters: :カラム名とコマンドプロンプトに表れていた。
#実際にパラメータの受け渡しがされていなかったので、次のページでは受け取ったパラメータが表示されるはずが空白になっていた。ようこそ～さん！の～の部分のこと。
end

app/controllers/members/application_controller.rb
class Members::ApplicationController < ActionController::Base
  layout 'members'
before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
      member_top_path
  end


  def after_sign_out_path_for(resource)
      new_member_session_path
  end


  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])# 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
      devise_parameter_sanitizer.permit(:sign_in, keys:[:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end
#オカタクメモ1：上記のcofigure(以下ストロングパラメーターが分かりやすいのでそう呼ぶ)以下の記載がないとunpermitted.parameters: :カラム名とコマンドプロンプトに表れていた。
#実際にパラメータの受け渡しがされていなかったので、次のページでは受け取ったパラメータが表示されるはずが空白になっていた。ようこそ～さん！の～の部分のこと。
end

app/controllers/members/base.rb
class Members::Base < ApplicationController

  layout 'members'
before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
      items_path
  end


  def after_sign_out_path_for(resource)
      new_member_session_path
  end


  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])# 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end
#オカタクメモ1：上記のcofigure(以下ストロングパラメーターが分かりやすいのでそう呼ぶ)以下の記載がないとunpermitted.parameters: :カラム名とコマンドプロンプトに表れていた。
#実際にパラメータの受け渡しがされていなかったので、次のページでは受け取ったパラメータが表示されるはずが空白になっていた。ようこそ～さん！の～の部分のこと。
end

app/controllers/members/carts_controller.rb
class Members::CartsController < Members::Base
   before_action :authenticate_member!
   before_action :set_member
  # # before_action :set_cart

  def create
    @cart = current_member.carts.build(cart_params)
    @current_item = Cart.find_by(item_id: @cart.item_id,member_id: @cart.member_id)
    if @current_item.nil?
      if @cart.save
        flash[:success] = 'カートに商品が追加されました！'
        redirect_to carts_path
      else
        @carts = @member.carts.all
        render 'index'
        flash[:danger] = 'カートに商品を追加できませんでした。'
      end
    else
      @current_item.amount += params[:amount].to_i
      @current_item.update(cart_params)
      redirect_to carts_path
    end
  end

  def index
  	@carts = @member.carts.all
  end

  def update
   	@cart = Cart.find(params[:id])
   	@cart.update(cart_params)
   	redirect_to carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])
		@cart.destroy
    redirect_to carts_path
  end


  def destroy_all
    @member.carts.destroy_all
    redirect_to carts_path
  end


  private

  def cart_params
   	params.require(:cart).permit(:member_id, :item_id, :amount)
  end

  def set_member
   	@member = current_member
  end


end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  layout 'members'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/genres_controller.rb
class Members::GenresController < Members::Base

  def show
  	@genre = Genre.find(params[:id])
  	@genres = Genre.where(validity: true)
  	@items = @genre.items.includes(:genre).where(genres:{validity: true}).is_active
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :validity)
  end
end

app/controllers/members/home_controller.rb
class Members::HomeController < Members::Base
	before_action :set_genres
  before_action :set_items

  def top
      @item = Item.where(is_active: true)
      @all_ranks = Item.find(OrderItem.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  def about
  end

  private
  def set_genres
  	@genres = Genre.where(validity: true)
  end

  def set_items
     @all_rankings = Item.find(Like.group(:item_id).order('count(item_id) desc').pluck(:item_id))
  end

end

app/controllers/members/items_controller.rb
class Members::ItemsController < Members::Base
  before_action :set_genres

  def index

  #キーワードが入力されていれば、whereメソッドとLIKE検索（部分一致検索）を組み合わせて、必要な情報のみ取得する。
    @genres = Genre.where(validity: true)
    @items = Item.where(genre_id: @genres.pluck(:id)).where(is_active: true)
    @items = @items.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
    @all_ranks = Item.find(OrderItem.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  def show
  	@item = Item.find(params[:id])
  	@cart = @item.carts.build
    @all_ranks = Item.find(OrderItem.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  private
  def item_params
    params.require(:item).permit(:name, :detail, :img, :price, :genre_id, :is_active)
  end

  def set_genres
    @genres = Genre.where(validity: true)
  end

end

app/controllers/members/likes_controller.rb
class Members::LikesController < Members::Base
	def create
		item = Item.find(params[:item_id])
		like = current_member.likes.new(item_id: item.id)
		like.save
		redirect_to item_path(item)
	end

	def destroy
		item = Item.find(params[:item_id])
		like = current_member.likes.find_by(item_id: item.id)
		like.destroy
		redirect_to item_path(item)
	end
end

app/controllers/members/members_controller.rb
class Members::MembersController < Members::Base

  def show
    @member = current_member #params[:id]だと今回はurlにidを載せないようにしているのでcurrent_memberにしてログイン者のidを取得しています。オカタク。
  end

  def edit

    @member = current_member
  end
  def update
    @member = current_member
    @member.update(member_params)
    flash[:success]="変更が正常に登録されました。"
    redirect_to members_my_page_path
  end
  def unsubscribe
    @member = current_member
  end

  def withdraw
    @member = current_member
    @member.update(is_deleted: true)
    flash[:success]="ご愛顧ありがとうございました。またのご利用お待ちしております。"
    redirect_to top_path_path
  end
  def edit_pass
    @member = current_member
  end
  def update_pass
    @member = current_member
    new_password = params[:password]
    password_confirmation = params[:password_confirmation]
    if new_password ==password_confirmation
      if @member.reset_password(new_password,new_password)
       flash[:success]="パスワード変更に成功しました。"
       redirect_to new_member_session_path
       return
      else
        render "edit_pass"
      end
    else
      flash[:error]="パスワードが一致しません。"
      redirect_to members_edit_pass_path
    end
    end

  private
  def member_params
    params.require(:member).permit(:is_deleted, :encrypted_password, :email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)

  end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'members'
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/orders_controller.rb
class Members::OrdersController < Members::Base

  before_action :set_member
  def new
  	@order = Order.new
  end

  def create
     if current_member.carts.exists?
       @order = Order.new(orders_params)
       @order.member_id = current_member.id

       @add = params[:order][:add].to_i
       case @add
       when 1
         @order.postal_code = @member.postal_code
         @order.address = @member.address
         @order.name = @member.last_name && @member.first_name
       when 2
         @order.postal_code = params[:order][:postal_code]
         @order.address = prams[:order][:address]
         @order.name = params[:order][:name]
       when 3
         @order.postal_code = params[:order][:postal_code]
         @order.address = params[:order][:address]
         @order.name = params[:order][:name]
       end
        @order.save

       if Address.find_by(address: @order.address).nil?
         @address = Address.new
         @address.postal_code = @order.postal_code
         @address.address = @order.address
         @address.name = @order.name
         @address.member_id = current_member.id
         @address.save
       end

       current_member.carts.each do |cart|
         order_item = @order.order_items.build
         order_item.order_id = @order.id
         order_item.item_id = cart.item_id
         order_item.amount = cart.amount
         order_item.past_price = cart.item.price
         order_item.save
         cart.destroy
       end
         render :thanks
     else
       redirect_to top_path_url
     end
  end



  def confirm
    @order = Order.new(orders_params)
    @carts = current_member.carts
    @order.payment_method = params[:order][:payment_method]
    @add = params[:order][:add].to_i
    case @add

    when 1
      @order.postal_code = @member.postal_code
      @order.address = @member.address
      @order.name = @member.last_name
    when 2
      @sta = params[:order][:address].to_i
      @address = Address.find(@sta)
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
    when 3
      @order.postal_code = params[:order][:new_add][:postal_code]
      @order.address = params[:order][:new_add][:address]
      @order.name = params[:order][:new_add][:name]
    end
  end

  def thanks
  end

  def index
    @orders = @member.orders
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(orders_params)
  end

  private

  def orders_params
  	params.require(:order).permit(:member_id,:payment_method, :order_status, :postal_code, :address, :name, :deliver_charge, :total_payment, order_items_attributes: [:order_id, :item_id, :amount, :past_price, :making_status])
  end

  def set_member
    @member = current_member
  end

end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  layout 'members'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/views/members/orders/confirm.html.erb
<div id="wrapper">
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-7">
			<h3 class="heading">注文情報確認</h3>
			<!--注文商品一覧-->
			<%= form_with(model: @order, local:true) do |f| %>
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>商品名</th>
							<th>単価（税込）</th>
							<th>数量</th>
							<th>小計</th>
						</tr>
					</thead>

					<tbody>
						<% sum_all = 0 %>
						<% @carts.each do |cart| %>
						<tr>
							<td><%= cart.item.name %></td>
							<td><%= price_include_tax(cart.item.price) %></td>
							<td><%= cart.amount %></td>
							<td><%= sum_item = price_include_tax(cart.item.price).to_i * cart.amount  %>
								<% sum_all += sum_item.to_i %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
				<!--支払方法確認-->
				<h5 class="heading">支払方法</h4>
				<%= @order.payment_method %>
				<h5 class="heading">お届け先</h4>
				<%= @order.postal_code %>
      			<%= @order.address %>
      			<%= @order.name %>
		</div>
		<div class="col-xs-3">
			<table class="table table-bordered">
				<h1>　　　　　　　　　</h1>
				<tr>
					<th>送料</th><td><%= @order.deliver_charge %></td>
				</tr>
			    <tr>
					<th>商品合計</th><td><%= sum_all %></td>
				</tr>
				<tr>
					<th>請求額</th><td><%= total_payment = sum_all + @order.deliver_charge %></td>
			<!-- 瀬尾：請求額コードがありましたが、エラーが発生していましたので、作業を進めるため一旦削除しています。コンフリクトが起きた際はダーオカさんのコードを優先させてください。 -->
				</tr>
			</table>
			<%= f.hidden_field :member_id, :value => current_member.id %>
			<%= f.hidden_field :postal_code, :value => "#{@order.postal_code}" %>
			<%= f.hidden_field :address, :value => "#{@order.address}" %>
			<%= f.hidden_field :name, :value => "#{@order.name}" %>

			<%= f.submit "購入を確定する", class:"btn btn-primary" %>
			<% end %>
		</div>
		<div class="col-xs-1"></div>
	</div>
</div>

app/views/members/orders/index.html.erb
<div id="wrapper">
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-10">
			<h3 class="heading">注文履歴一覧</h3>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th style="text-align:center;">注文日</th>
						<th style="text-align:center;">配送先</th>
						<th style="text-align:center;">注文商品</th>
						<th style="text-align:center;">支払金額</th>
						<th style="text-align:center;">ステータス</th>
						<th style="text-align:center;">注文詳細</th>
					</tr>
				</thead>
				<tbody>
					<% @orders.each do |order| %>
					<tr>
						<td><%= order.created_at.strftime('%Y/%m/%d') %></td>
						<td>
							<%= order.postal_code %><br>
							<%= order.address %><br>
							<%= order.name %>
						</td>
						<% sum_all = 0 %>
						<td style="overflow:hidden; text-overflow:ellipsis;">
							<% order.order_items.each do |order_item| %>
								<%= order_item.item.name %><br>
							<% sub_total = price_include_tax(order_item.item.price).to_i * order_item.amount %>
							<% sum_all += sub_total.to_i %>
							<% end %>
						</td>
						<td><%= sum_all += order.deliver_charge.to_i %></td>
						<td><%= order.order_status %></td>
						<td><%= link_to "表示する", order_path(order.id), class:"btn btn-primary"  %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<div class="col-xs-1"></div>
	</div>
</div>

app/views/members/orders/new.html.erb
<div id="wrapper">
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-10">
	<div class="order-new-title">
		<h3 class="heading">注文情報確認</h3>
	   </div>
			<%= form_with(model: @order, local: true, url:{action: 'confirm'}) do |f| %>

			<!--支払方法-->
			<div class="order-new-payment-title">
				<strong>支払方法</strong>
			</div>
			<div class="order-payment">
				<br><label class="btn btn-outline-secondary" style="width:80px height:80px">
					<%= f.radio_button :payment_method, :クレジットカード %>
					<%= f.label :クレジットカード, class:"payment_method_label" %>
				</label>
				<br><label class="btn btn-outline-secondary" style="width:80px height:80px">
					<%= f.radio_button :payment_method, :銀行振込 %>
					<%= f.label :銀行振込, class:"payment_method_label" %>
				</label>
			</div>
			<div class="order-address-title">
				<br><strong>お届け先</strong>
			</div>
			<!--自身の住所-->
			<div class="order-address">
				<p>
					<label><%= f.radio_button :add, 1, checked:true, checked: "checked" %>ご自身の住所</label><br>
					<%= @member.postal_code %>
					<%= @member.address %>
					<%= @member.last_name %>
					<%= @member.first_name %>
				</p>
				<!--登録済住所-->
				<p><label><%= f.radio_button :add, 2, style: "display: inline-block" %>登録済住所から選択</label><br>
					<%= f.collection_select :address, @member.addresses, :id, :address %>
				</p>
						<!--新しい住所-->
				<p><label><%= f.radio_button :add, 3 %>新しいお届け先</label></p>
					<%= f.fields_for :new_add do |new_add| %>
						<strong>郵便番号（ハイフンなし）</strong>
							<%= new_add.text_field :postal_code, class:'form-control' %>
						<strong>住所</strong>
							<%= new_add.text_field :address, class:'form-control' %>
						<strong>宛名</strong>
							<%= new_add.text_field :name, class:'form-control' %>
					<% end %>
					<div class="confirm-btn">
						<%= f.submit "確認画面へ進む", class:"btn btn-primary" %>
					</div>
				<% end %>
			</div>
		<div class="col-xs-1"></div>
	</div>
</div>

app/views/members/orders/show.html.erb
<div id="wrapper">
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-7">
			<h3 class="heading">注文履歴詳細</h3>
			<p><strong>注文情報</strong></p>
			<table class="table table-borderd">
				<tr>
					<th>注文日</th><td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
				</tr>
				<tr>
					<th>配送先</th><td><%= @order.postal_code %><%= @order.address %><%= @order.name %></td>
				</tr>
				<tr>
					<th>支払方法</th><td><%= @order.payment_method %></td>
				</tr>
				<tr>
					<th>ステータス</th><td><%= @order.order_status %></td>
				</tr>
			</table>
			<P><strong>注文内容</strong></P>
			<table class="table table-borderd">
				<thead>
					<tr>
						<th>商品</th>
						<th>単価（税込）</th>
						<th>個数</th>
						<th>小計</th>
					</tr>
				</thead>
				<% sum_all = 0 %>
				<% @order.order_items.each do |order_item| %>
				<tbody>
					<tr>
						<td><%= order_item.item.name %></td>
						<td><%= price_include_tax(order_item.item.price) %></td>
						<td><%= order_item.amount %></td>
						<td><%= sum_item = price_include_tax(order_item.item.price).to_i * order_item.amount %></td>
						<% sum_all += sum_item.to_i %>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div>
		<div class="col-xs-3">
			<h1>　　　</h1>
			<p><strong>請求情報</strong></p>
			<table class="table table-borderd">
				<tr>
					<th class="success">商品合計</th><td><%= sum_all %></td>
				</tr>
			    <tr>
					<th class="success">配送料</th><td><%= @order.deliver_charge %></td>
				</tr>
				<tr>
					<th class="success">ご請求額</th><td><%= total_payment = sum_all + @order.deliver_charge %></td>
				</tr>
			</table>
		</div>
		<div class="col-xs-1"></div>
	</div>
</div>

app/views/members/orders/thanks.html.erb
<div id="wrapper">
<div class="row">
		<div class="col-xs-2"></div>
		<div class="col-xs-8">
			<h1>ご購入ありがとうございます</h1>
			<p><%= link_to "HOMEへ戻る", top_path_url %></p>
		</div>
		<div class="col-xs-2"></div>
	</div>
</div>