config/routes.rb
Rails.application.routes.draw do


#会員側のルーティング#

  scope module: :members do
    get '/' => 'home#top', as: 'top_path'
    get 'home/about' => 'home#about'
    get 'members/my_page' => 'members#show'
    get 'members/unsubscribe' => 'members#unsubscribe'
    patch 'members/withdraw' => 'members#withdraw'
    get 'members/edit_pass' => 'members#edit_pass'
    patch 'members/update_pass' => 'members#update_pass'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resource :members, only: [:edit, :update, :show]
    resources :carts, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    
    resources :items, only: [:index, :show] do
      resource :likes, only: [:create, :destroy]
    end
    
    resources :genres, only: [:show]
    resources :items, only: [:index, :show] do
      # collection do
      #   search 'search'
      # end
    end

    resources :genres, only: [:show]
    resources :orders, only: [:index, :new, :create, :show, :update]
    post 'order/confirm' => 'orders#confirm', as: 'order_confirm'
    get "order/thanks" => 'orders#thanks', as: 'order_thanks'

    devise_for :members

  end

  #管理者側のルーティング

  namespace :admins do
    get '' => 'tops#top'
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    resources :items, only: [:index, :show, :edit, :update, :create, :new]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :members, only: [:index, :show, :edit, :update] do
    get "orders/confirm"
    end
  end

  scope module: :admins do #URLがadmins_admins_sign_inのように冗長にならないようにscope muduleを使用
    devise_for :admins
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

	scope :is_active, -> { where(is_active: true)}

	belongs_to :genre
	has_many :carts
	has_many :members, through: :carts
	has_many :order_items
	has_many :order, through: :order_items
	has_many :likes, dependent: :destroy

	def liked_by?(member)
		likes.where(member_id: member.id).exists?
	end

	attachment :img
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < Admins::Base
  before_action :set_genres, only: [:index, :new, :edit, :create, :update]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admins_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admins_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:name, :detail, :img, :price, :genre_id, :is_active)
  end

  def set_genres
      @genres = Genre.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@items = Item.all
  end

  def show
  end
end

app/controllers/members/items_controller.rb
class Members::ItemsController < Members::Base
  before_action :set_genres

  def index

  #キーワードが入力されていれば、whereメソッドとLIKE検索（部分一致検索）を組み合わせて、必要な情報のみ取得する。
    @genres = Genre.where(validity: true)
    @items = Item.where(genre_id: @genres.pluck(:id)).where(is_active: true)
    @items = @items.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
    @all_ranks = Item.find(OrderItem.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  def show
  	@item = Item.find(params[:id])
  	@cart = @item.carts.build
    @all_ranks = Item.find(OrderItem.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  private
  def item_params
    params.require(:item).permit(:name, :detail, :img, :price, :genre_id, :is_active)
  end

  def set_genres
    @genres = Genre.where(validity: true)
  end

end

app/helpers/member/items_helper.rb
module Member::ItemsHelper
end

app/views/admins/items/edit.html.erb
<div id="wrapper">
    <div class="row">
	    <div class="col-xs-1"></div>
	    <div class="col-xs-10">
			<%= form_with model:@item, url: admins_item_path, local: true do |f| %>
			<h3 class="heading">商品編集</h3>
			<div class="container">
				<div class="row">
				    <div class="col-sm-3">
				    	<div align="center">
				    		<%= attachment_image_tag @item, :img, class: "img-square", format: 'jpeg', fallback: "no_image.jpg", size: "200x200" %>
							<%= f.attachment_field :img, placeholder: "商品画像", class: "image-prev" %>
				    	</div>
					</div>
					<div class="col-sm-6">
						<table class="table table-bordered">
							<tbody>
								<tr>
									<th>商品名</th>
									<td><%= f.text_field :name, class:"form-control", placeholder:"商品名" %></td>
								</tr>
								<tr>
									<th>商品説明</th>
									<td><%= f.text_field :detail, class:"form-control", placeholder:"商品説明" %></td>
								</tr>
								<tr>
									<th>ジャンル</th>
									<td><%= f.collection_select :genre_id, @genres, :id, :name %></td>
								</tr>
								<tr>
									<th>税抜価格</th>
									<td><%= f.text_field :price, class:"form-control", placeholder:"税抜価格" %>円</td>
								</tr>
								<tr>
									<th>販売ステータス</th>
									<td><%= f.select :is_active ,[['販売中',true],['売り切れ',false]] %></td>
								</tr>
							</tbody>
						</table>
						<div align="right"><%= f.submit '変更を保存' %></div>
					</div>
				</div>
				<div class="col-sm-3"></div>
				<% end %>
			</div>
		<div class="col-xs-1"></div>
	</div>
</div>

app/views/admins/items/index.html.erb
<div id="wrapper">
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
      <h3 class="heading">商品一覧</h3>
      <div align="right"><%= link_to image_tag("plus_icon.png",size: "30x30"), new_admins_item_path %></td>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admins_item_path(item), class: "item_#{item.id}" %></td>
            <td><%= item.price %></td>
            <td><%= item.genre.name if item.genre.present? %></td>
            <% if item.is_active == true %>
            <td>販売中</td>
            <% else %>
            <td>売り切れ</td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-xs-1"></div>
  </div>
</div>

app/views/admins/items/new.html.erb
<div id="wrapper">
    <div class="row">
	    <div class="col-xs-1"></div>
	    <div class="col-xs-10">
			<h3 class="heading">商品新規登録</strong></h4>
			<%= form_with model:@item, url: admins_items_path, local: true do |f| %>
				<div class="row">
				    <div class="col-sm-5">
				    	<div align="center">
				    	<%= attachment_image_tag @item, :img, class: "img-square", fallback: "no_image.jpg", size:"200x200" %>
				    	<%= f.attachment_field :img, placeholder: "商品画像", class: "image-prev" %>
				    	</div>
				    </div>
				    <div class="col-sm-7">
				    	商品名
				    	<%= f.text_field :name, class:"form-control", placeholder:"商品名" %>
				    	商品説明
				    	<%= f.text_area :detail, class:"form-control", placeholder:"商品説明" %>
				    	ジャンル
				    	<%= f.collection_select :genre_id, @genres, :id, :name %>
				    	<br>税抜価格
				    	<%= f.text_field :price, class:"form-control", placeholder:"税抜価格" %>円
				    </div>
				</div>
				<div align="right"><%= f.submit "新規登録" %></div>
			<% end %>
		</div>
		<div class="col-xs-1"></div>
	</div>
</div>

app/views/admins/items/show.html.erb
<div id="wrapper">
    <div class="row">
	    <div class="col-xs-1"></div>
	    <div class="col-xs-10">
			<h3 class="heading">商品詳細</h3>
			<div class="container">
				<div class="row">
				    <div class="col-sm-3">
				    	<div align="center">
				    		<%= attachment_image_tag @item, :img, format: 'jpeg', fallback: "no_image.jpg", size: "200x200" %>
				    	</div>
					</div>
					<div class="col-sm-6">
						<table class="table table-bordered">
							<tbody>
								<tr>
									<td><strong>商品名</strong></td>
									<td><%= @item.name %><br></td>
								</tr>
								<tr>
									<td><strong>商品説明</strong></td>
									<td><%= @item.detail %><br></td>
								</tr>
								<tr>
									<td><strong>ジャンル</strong></td>
									<td><%= @item.genre.name %></td>
								</tr>
								<tr>
									<td><strong>価格</strong></td>
									<td><%= @item.price %>(<%= tax(@item.price) %>)円</td>
								</tr>
								<tr>
									<td><strong>販売ステータス</strong></td>
									<% if @item.is_active == true %>
									<td>販売中</td>
									<% else %>
									<td>売り切れ</td>
									<% end %>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="col-sm-3">
				</div>
			</div>
		</div>
		<div class="col-xs-1"></div>
	</div>
</div>
<div align="right"><button type="button" class="btn btn-secondary"><%= link_to "編集する", edit_admins_item_path(@item) %></button></div>