config/routes.rb
Rails.application.routes.draw do


#会員側のルーティング#

  scope module: :members do
    get '/' => 'home#top', as: 'top_path'
    get 'home/about' => 'home#about'
    get 'members/my_page' => 'members#show'
    get 'members/unsubscribe' => 'members#unsubscribe'
    patch 'members/withdraw' => 'members#withdraw'
    get 'members/edit_pass' => 'members#edit_pass'
    patch 'members/update_pass' => 'members#update_pass'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resource :members, only: [:edit, :update, :show]
    resources :carts, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    
    resources :items, only: [:index, :show] do
      resource :likes, only: [:create, :destroy]
    end
    
    resources :genres, only: [:show]
    resources :items, only: [:index, :show] do
      # collection do
      #   search 'search'
      # end
    end

    resources :genres, only: [:show]
    resources :orders, only: [:index, :new, :create, :show, :update]
    post 'order/confirm' => 'orders#confirm', as: 'order_confirm'
    get "order/thanks" => 'orders#thanks', as: 'order_thanks'

    devise_for :members

  end

  #管理者側のルーティング

  namespace :admins do
    get '' => 'tops#top'
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    resources :items, only: [:index, :show, :edit, :update, :create, :new]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :members, only: [:index, :show, :edit, :update] do
    get "orders/confirm"
    end
  end

  scope module: :admins do #URLがadmins_admins_sign_inのように冗長にならないようにscope muduleを使用
    devise_for :admins
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/members_controller.rb
class Admins::MembersController < Admins::Base

  def index
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admins_member_path(@member), success: 'お客様情報が更新されました！'
    else
      flash[:danger] = 'お客様の情報を更新出来ませんでした。空欄の箇所はありませんか？'
      render :index
    end
  end


  private
  def member_params
    params.require(:member).permit(:is_deleted, :email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)
  end
end

app/controllers/members/addresses_controller.rb
class Members::AddressesController < Members::Base

  before_action :set_member

  def index
    @address = Address.new
    @addresses = @member.addresses
  end

  def create
    @address = Address.new(address_params)
    @address.member_id = current_member.id
    @address.save
    redirect_to addresses_path
  end

  def edit
    @address = Address.find(params[:id])

  end

  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to addresses_path
  end

  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to addresses_path

  end

  private

  def set_member
    @member = current_member
  end
  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end

end

app/controllers/members/application_controller copy.rb
class Members::ApplicationController < ActionController::Base
  layout 'members'
before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
      member_top_path
  end


  def after_sign_out_path_for(resource)
      new_member_session_path
  end


  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])# 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
      devise_parameter_sanitizer.permit(:sign_in, keys:[:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end
#オカタクメモ1：上記のcofigure(以下ストロングパラメーターが分かりやすいのでそう呼ぶ)以下の記載がないとunpermitted.parameters: :カラム名とコマンドプロンプトに表れていた。
#実際にパラメータの受け渡しがされていなかったので、次のページでは受け取ったパラメータが表示されるはずが空白になっていた。ようこそ～さん！の～の部分のこと。
end

app/controllers/members/application_controller.rb
class Members::ApplicationController < ActionController::Base
  layout 'members'
before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
      member_top_path
  end


  def after_sign_out_path_for(resource)
      new_member_session_path
  end


  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])# 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
      devise_parameter_sanitizer.permit(:sign_in, keys:[:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end
#オカタクメモ1：上記のcofigure(以下ストロングパラメーターが分かりやすいのでそう呼ぶ)以下の記載がないとunpermitted.parameters: :カラム名とコマンドプロンプトに表れていた。
#実際にパラメータの受け渡しがされていなかったので、次のページでは受け取ったパラメータが表示されるはずが空白になっていた。ようこそ～さん！の～の部分のこと。
end

app/controllers/members/base.rb
class Members::Base < ApplicationController

  layout 'members'
before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
      items_path
  end


  def after_sign_out_path_for(resource)
      new_member_session_path
  end


  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])# 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :encrypted_password, :last_name,
      :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end
#オカタクメモ1：上記のcofigure(以下ストロングパラメーターが分かりやすいのでそう呼ぶ)以下の記載がないとunpermitted.parameters: :カラム名とコマンドプロンプトに表れていた。
#実際にパラメータの受け渡しがされていなかったので、次のページでは受け取ったパラメータが表示されるはずが空白になっていた。ようこそ～さん！の～の部分のこと。
end

app/controllers/members/carts_controller.rb
class Members::CartsController < Members::Base
   before_action :authenticate_member!
   before_action :set_member
  # # before_action :set_cart

  def create
    @cart = current_member.carts.build(cart_params)
    @current_item = Cart.find_by(item_id: @cart.item_id,member_id: @cart.member_id)
    if @current_item.nil?
      if @cart.save
        flash[:success] = 'カートに商品が追加されました！'
        redirect_to carts_path
      else
        @carts = @member.carts.all
        render 'index'
        flash[:danger] = 'カートに商品を追加できませんでした。'
      end
    else
      @current_item.amount += params[:amount].to_i
      @current_item.update(cart_params)
      redirect_to carts_path
    end
  end

  def index
  	@carts = @member.carts.all
  end

  def update
   	@cart = Cart.find(params[:id])
   	@cart.update(cart_params)
   	redirect_to carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])
		@cart.destroy
    redirect_to carts_path
  end


  def destroy_all
    @member.carts.destroy_all
    redirect_to carts_path
  end


  private

  def cart_params
   	params.require(:cart).permit(:member_id, :item_id, :amount)
  end

  def set_member
   	@member = current_member
  end


end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  layout 'members'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/genres_controller.rb
class Members::GenresController < Members::Base

  def show
  	@genre = Genre.find(params[:id])
  	@genres = Genre.where(validity: true)
  	@items = @genre.items.includes(:genre).where(genres:{validity: true}).is_active
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :validity)
  end
end

app/controllers/members/home_controller.rb
class Members::HomeController < Members::Base
	before_action :set_genres
  before_action :set_items

  def top
      @item = Item.where(is_active: true)
      @all_ranks = Item.find(OrderItem.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  def about
  end

  private
  def set_genres
  	@genres = Genre.where(validity: true)
  end

  def set_items
     @all_rankings = Item.find(Like.group(:item_id).order('count(item_id) desc').pluck(:item_id))
  end

end

app/controllers/members/items_controller.rb
class Members::ItemsController < Members::Base
  before_action :set_genres

  def index

  #キーワードが入力されていれば、whereメソッドとLIKE検索（部分一致検索）を組み合わせて、必要な情報のみ取得する。
    @genres = Genre.where(validity: true)
    @items = Item.where(genre_id: @genres.pluck(:id)).where(is_active: true)
    @items = @items.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
    @all_ranks = Item.find(OrderItem.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  def show
  	@item = Item.find(params[:id])
  	@cart = @item.carts.build
    @all_ranks = Item.find(OrderItem.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  private
  def item_params
    params.require(:item).permit(:name, :detail, :img, :price, :genre_id, :is_active)
  end

  def set_genres
    @genres = Genre.where(validity: true)
  end

end

app/controllers/members/likes_controller.rb
class Members::LikesController < Members::Base
	def create
		item = Item.find(params[:item_id])
		like = current_member.likes.new(item_id: item.id)
		like.save
		redirect_to item_path(item)
	end

	def destroy
		item = Item.find(params[:item_id])
		like = current_member.likes.find_by(item_id: item.id)
		like.destroy
		redirect_to item_path(item)
	end
end

app/controllers/members/members_controller.rb
class Members::MembersController < Members::Base

  def show
    @member = current_member #params[:id]だと今回はurlにidを載せないようにしているのでcurrent_memberにしてログイン者のidを取得しています。オカタク。
  end

  def edit

    @member = current_member
  end
  def update
    @member = current_member
    @member.update(member_params)
    flash[:success]="変更が正常に登録されました。"
    redirect_to members_my_page_path
  end
  def unsubscribe
    @member = current_member
  end

  def withdraw
    @member = current_member
    @member.update(is_deleted: true)
    flash[:success]="ご愛顧ありがとうございました。またのご利用お待ちしております。"
    redirect_to top_path_path
  end
  def edit_pass
    @member = current_member
  end
  def update_pass
    @member = current_member
    new_password = params[:password]
    password_confirmation = params[:password_confirmation]
    if new_password ==password_confirmation
      if @member.reset_password(new_password,new_password)
       flash[:success]="パスワード変更に成功しました。"
       redirect_to new_member_session_path
       return
      else
        render "edit_pass"
      end
    else
      flash[:error]="パスワードが一致しません。"
      redirect_to members_edit_pass_path
    end
    end

  private
  def member_params
    params.require(:member).permit(:is_deleted, :encrypted_password, :email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)

  end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'members'
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/orders_controller.rb
class Members::OrdersController < Members::Base

  before_action :set_member
  def new
  	@order = Order.new
  end

  def create
     if current_member.carts.exists?
       @order = Order.new(orders_params)
       @order.member_id = current_member.id

       @add = params[:order][:add].to_i
       case @add
       when 1
         @order.postal_code = @member.postal_code
         @order.address = @member.address
         @order.name = @member.last_name && @member.first_name
       when 2
         @order.postal_code = params[:order][:postal_code]
         @order.address = prams[:order][:address]
         @order.name = params[:order][:name]
       when 3
         @order.postal_code = params[:order][:postal_code]
         @order.address = params[:order][:address]
         @order.name = params[:order][:name]
       end
        @order.save

       if Address.find_by(address: @order.address).nil?
         @address = Address.new
         @address.postal_code = @order.postal_code
         @address.address = @order.address
         @address.name = @order.name
         @address.member_id = current_member.id
         @address.save
       end

       current_member.carts.each do |cart|
         order_item = @order.order_items.build
         order_item.order_id = @order.id
         order_item.item_id = cart.item_id
         order_item.amount = cart.amount
         order_item.past_price = cart.item.price
         order_item.save
         cart.destroy
       end
         render :thanks
     else
       redirect_to top_path_url
     end
  end



  def confirm
    @order = Order.new(orders_params)
    @carts = current_member.carts
    @order.payment_method = params[:order][:payment_method]
    @add = params[:order][:add].to_i
    case @add

    when 1
      @order.postal_code = @member.postal_code
      @order.address = @member.address
      @order.name = @member.last_name
    when 2
      @sta = params[:order][:address].to_i
      @address = Address.find(@sta)
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
    when 3
      @order.postal_code = params[:order][:new_add][:postal_code]
      @order.address = params[:order][:new_add][:address]
      @order.name = params[:order][:new_add][:name]
    end
  end

  def thanks
  end

  def index
    @orders = @member.orders
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(orders_params)
  end

  private

  def orders_params
  	params.require(:order).permit(:member_id,:payment_method, :order_status, :postal_code, :address, :name, :deliver_charge, :total_payment, order_items_attributes: [:order_id, :item_id, :amount, :past_price, :making_status])
  end

  def set_member
    @member = current_member
  end

end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  layout 'members'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  layout 'members'
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/member/addresses_helper.rb
module Member::AddressesHelper
end

app/views/members/members/edit.html.erb
<div id="wrapper">
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-10">
		<h3 class="heading">登録情報編集</h3>
		<%= form_with model:@member, url:members_path(@member.id) do |f| %>
		<table class="table table-bordered" >
		    <tr>
		  	 	<th>名前</th>
		  	  	<td>(姓)<%= f.text_field :last_name, class:"form-control" %></td>
				<td>(名)<%= f.text_field :first_name, class:"form-control" %></td>
		    </tr>
			<tr>
			    <th>フリガナ</th>
			    <td>(セイ)<%= f.text_field :last_name_kana, class:"form-control" %></td>
				<td>(メイ)<%= f.text_field :first_name_kana, class:"form-control" %></td>
			</tr>
			<tr>
			    <th><%= "メールアドレス" %></th>
			    <td><%= f.text_field :email, class:"form-control" %></td>
			</tr>
			<tr>
			  	<th><%= "郵便番号(ハイフンなし)" %></th>
			    <td><%= f.text_field :postal_code, class:"form-control" %></td>
			</tr>
			<tr>
			    <th><%= "住所" %></th>
			    <td><%= f.text_field :address, class:"form-control" %></td>
			</tr>
			<tr>
			    <th><%= "電話番号(ハイフンなし)" %></th>
			    <td><%= f.text_field :telephone_number, class:"form-control" %></td>
			</tr>
		</table>
			<tr>
		        <th><%= f.submit "変更を保存", class:"btn btn-primary" %></th>
		        <th><%= link_to "退会する", members_unsubscribe_path %></th>
	        </tr>
		<% end %>
		</div>
		<div class="col-xs-1"></div>
	</div>
</div>

app/views/members/members/edit_pass.html.erb
<div id="wrapper">
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-10">
			<%= flash[:error] %>
<% if @member.errors.any? %>
	<h3><%= @member.errors.count%>個の誤りがあります。</h3>
		<% @member.errors.full_messages.each do |msg| %>
			<%= msg %>
		<% end %>
<% end %>
			<h3 class="heading">登録情報編集</h3>
			<%= form_with url: members_update_pass_path, local:true, method: :patch do |f| %>
			    <table>
					<tr>
						<th><%= "パスワード" %></th>
						<td><%= f.password_field :password, class:"form-control" %></td>
					</tr>
					<tr>
						<th><%= "パスワード確認用" %></th>
						<td><%= f.password_field :password_confirmation, class:"form-control" %></td>
					</tr>
					<tr>
			        	<th><%= f.submit "変更を保存", class:"btn btn-primary" %></th>
			        </tr>
			    </table>
			<% end %>
		</div>
		<div class="col-xs-1"></div>
	</div>
</div>

app/views/members/members/show.html.erb
<div id="wrapper">
  <%=flash[:success]%>
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-10">

		  <h3 class="heading">マイページ</h3>
			<div class="register-info">
			<h4><strong>登録情報</strong></h4>
			</div>
			<%= link_to "編集する" , edit_members_path, class:"btn btn-primary" %>
			<%= link_to "パスワードを変更する", members_edit_pass_path, class:"btn btn-primary" %>
        		<table class="table table-bordered" >
					 <tr>
					   <th><%= "氏名" %></th>
					   <td><%= current_member.last_name %><%= current_member.first_name %></td>
					 </tr>
					 <tr>
					   <th><%= "カナ" %></th>
					   <td><%= current_member.last_name_kana %><%= current_member.first_name_kana %></td>
					 </tr>
					 <tr>
					   <th><%= "郵便番号" %></th>
					   <td><%= current_member.postal_code %></td>
					 </tr>
					 <tr>
					  <th><%= "住所" %></th>
					  <td><%= current_member.address %></td>
					 </tr>
					 <tr>
					  <th><%= "電話番号" %></th>
					  <td><%= current_member.telephone_number %></td>
					 </tr>
					 <tr>
					  <th><%= "メールアドレス" %></th>
					  <td><%= current_member.email %></td>
					 </tr>
				 </table>
					<div class="member-show-address">
					   <h4><strong>配送先　　</strong></h4><%= link_to "一覧を見る", addresses_path, class:"btn btn-primary" %>
					</div>
					<div class="member-show-order">
					   <h4><strong>注文履歴　</strong></h4> <%= link_to "一覧を見る", orders_path, class:"btn btn-primary" %>
					</div>
		</div>
		<div class="col-xs-1"></div>
	</div>
</div>

app/views/members/members/unsubscribe.html.erb
<div id="wrapper">
  <div class="row">
    <div class="col-xs-3"></div>
    <div class="col-xs-6">
      <strong><p style="text-align:center;"><h5>本当に退会しますか？</h5></strong>
        <p style="text-align:center;">退会すると、会員登録情報や</p>
        <p style="text-align:center;">これまでの購入履歴が閲覧できなくなります。</p>
        <p style="text-align:center;">退会する場合は、「退会する」をクリックしてください。</p>
          <tr>
            <th><%= link_to "退会しない", members_my_page_path, class:"btn btn-primary" %></th>
          </tr>
          <tr>
           <th><%= link_to "退会する", members_withdraw_path, method: :patch, class:"btn btn-danger" %></th>
          </tr>
      </div>
      <div class="col-xs-3"></div>
  </div>
</div>

app/views/members/members/withdraw.html.erb
<div id="wrapper">
	<div class="row">
		<div class="col-xs-1"></div>
		<div class="col-xs-10">
		<h1>さいなら</h1>
		</div>
		<div class="col-xs-1"></div>
	</div>
</div>